version: '3.9'

services:
  postgres:
    image: postgres:16.4
    container_name: pg
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: testdb
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
  redis:
    image: redis:7.2.4-alpine
    container_name: redis
    ports:
      - "6379:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5
      
  clickhouse:
    image: clickhouse/clickhouse-server:24.3.6
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - ch_data:/var/lib/clickhouse
      - ./migrations/clickhouse/0001_init_logs.sql:/docker-entrypoint-initdb.d/0001_init_logs.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:8123/ping"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats:
    image: nats:2.10.11-alpine
    container_name: nats
    command: "--http_port 8222"
    ports:
      - "4222:4222"      
      - "8222:8222"    
    healthcheck:
      test: ["CMD-SHELL", "timeout 5s wget --no-verbose --tries=1 --spider http://localhost:8222/healthz || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5

  nats-ui:
    image: sphqxe/nats-webui:latest
    container_name: nats-ui
    ports:
      - "8083:80"
    environment:
      - NATS_URL=nats://nats:4222
    depends_on:
      nats:
        condition: service_healthy
      
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: goods-service    
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
      clickhouse:
        condition: service_healthy
      nats:
        condition: service_started
    ports:
      - "8080:8080"
    environment:
      - POSTGRES_DSN=postgres://postgres:postgres@postgres:5432/testdb?sslmode=disable
      - REDIS_ADDR=redis:6379
      - NATS_URL=nats://nats:4222
      - CLICKHOUSE_URL=tcp://clickhouse:9000?database=logs
    restart: unless-stopped

volumes:
  pg_data:
  ch_data:
